export const locations = [
    {id: 'all', name: 'st andrews bubble (all locations)'},
    {id: 'market_street', name: 'market street'},
    {id: 'north_street', name: 'north street'},
    {id: 'south_street', name: 'south street'},
    {id: 'north_haugh', name: 'north haugh'},
    {id: 'union', name: 'union'},
    {id: 'main_library', name: 'main library'},
    {id: 'dra', name: 'dra & fife park'},
    {id: 'abh', name: 'abh & powell'},
    {id: 'andrew_melville', name: 'andrew melville'},
    {id: 'uni_hall', name: 'uni hall & whitehorn'},
    {id: 'jbh', name: 'john burnet'},
    {id: 'mcintosh', name: 'macintosh'},
    {id: 'st_regulus', name: 'st regulus'},
    {id: 'st_salvators', name: 'sally\'s & gannochy'},
    {id: 'deans_court', name: 'deans court'},
    {id: 'ayton', name: 'ayton house'},
    {id: 'east_shore', name: 'east shore'},
    {id: 'outskirts', name: 'outskirts (badlands)'}
];
