# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI Staging

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install firebase tools
      run: npm i -g firebase-tools
    - name: Install dependencies
      run: npm ci
    - name: Run build
      run: npm run build
    - name: Run test
      run: firebase emulators:exec --only database "npm run test-database"
    - name: Deploy firebase
      run: firebase -P staging deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
