# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI Test Build

on:
  pull_request:
    branches: [ dev, prod ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install firebase tools
      run: npm i -g firebase-tools
    - name: Install firebase-bolt
      run: npm i -g firebase-bolt
    - name: Install dependencies
      run: npm ci
    - name: Install functions dependencies
      run: npm --prefix ./functions ci
    - name: Run react build
      run: npm run build
    - name: Run database rules test
      run: firebase emulators:exec --only database "npm run test-database"
    - name: Run database rules conversion check
      run: firebase-bolt database.rules.bolt
    - name: Run functions lint
      run: npm --prefix ./functions run lint

